pipeline {
    
    agent any

    parameters {
        string(defaultValue: "jenkinsAwsCcEUCentral1", description: "AWS profile", name: "awsProfile")
    }
    
    stages {
        stage("building_aws_infra") {
            steps {
                sh "aws cloudformation create-stack --stack-name webhitz --template-body file:///var/jenkins_home/workspace/Webhitzz_infra/AWS_INFRA_CF/soloEC2wSSMwUb2004.yaml --capabilities CAPABILITY_NAMED_IAM --profile ${params.awsProfile}"
            }
        }
        stage("checking_cf building") {
            steps {
                
                sh """ \
                    status='' \
                    sleep 5 \
                    status=aws cloudformation describe-stack --stack-name webhitz --profile ${params.awsProfile} | grep StackStatus \
                    echo $status \
                   """
            }
        }
    }
}
