pipeline {
    agent any
    
    stages {
        stage("building_aws_infra") {
            steps {
                sh "/usr/local/bin/aws cloudformation create-stack --stack-name webhitzz_infra --template-body file://soloEC2wSSMUb2004.yaml --capabilities CAPABILITY_NAMED_IAM"
            }
        }
    }
}
